CREATE TABLE test_entries (
_id INTEGER PRIMARY KEY AUTOINCREMENT,
date TEXT NOT NULL,
ammonia REAL,
nitrite REAL,
nitrate REAL,
phosphate REAL,
alkilinity REAL,
calcium REAL,
magnesium REAL);

CREATE TABLE ammonia (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	value REAL,
	date TEXT NOT NULL);
CREATE TABLE nitrite (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	value REAL,
	date TEXT NOT NULL);
CREATE TABLE nitrate (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	value REAL,
	date TEXT NOT NULL);
CREATE TABLE phosphate (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	value REAL,
	date TEXT NOT NULL);
CREATE TABLE alkilinity (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	value REAL,
	date TEXT NOT NULL);
CREATE TABLE calcium (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	value REAL,
	date TEXT NOT NULL);
CREATE TABLE magnesium (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	value REAL,
	date TEXT NOT NULL);
CREATE TABLE iodine (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	value REAL,
	date TEXT NOT NULL);

